/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CltControl' at '14/12/17 13:06' with Gradle 2.14.1
 *
 * @author CltControl, @date 14/12/17 13:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
